feat: separating transactional and non-transactional queries
supertokens/supertokens-sql-plugin pull request #10
Opened 2022-03-15 13:21 UTC by anugrahsinghal

all queries do not need a transaction
so adding a new function to do non-transactional queries
and refactor names to better represent their usage

PR Template TBA

2022-03-15 17:16 UTC, rishabhpoddar requested changes

2022-03-15 17:16 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/ConnectionPool.java
> +    public static <T> T withConnectionWithoutTransaction(Start start, WithConnectionForComplexTransaction<T> func)
We don't need to create this extra function as it can be inside `withConnection` itself? Plus exposing this and `withConnection` can be confusing (which one should be used?)

2022-03-15 17:16 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/ConnectionPool.java
> +    public static <T> T withConnectionForTransaction(Start start, WithConnection<T> func)
We shouldn't expose this function and `withConnectionForComplexTransaction` (we just need one of these)

2022-03-15 17:30 UTC, closed without merging

2022-03-15 17:50 UTC, anugrahsinghal commented
reopening this PR

2022-03-16 11:49 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/ConnectionPool.java
> +    public static <T> T withConnectionWithoutTransaction(Start start, WithConnectionForComplexTransaction<T> func)
makes sense, will make changes

2022-03-16 11:54 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/ConnectionPool.java
> +    public static <T> T withConnectionForTransaction(Start start, WithConnection<T> func)
so there are actually two usage patterns that I noticed

- One where in a transaction the`StorageTransactionLogicException` can be thrown, it is used by `start.startTransaction`
- Second when some Queries classes are directly calling the `ConnectionPool. withConnectionForTransaction` method and it does not throw a `StorageTransactionLogicException`, it handles it and transforms to a `SQLException`


which usage pattern should be eliminated? @rishabhpoddar

2022-03-16 13:17 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/ConnectionPool.java
> +    public static <T> T withConnectionForTransaction(Start start, WithConnection<T> func)
new PR to resolve this https://github.com/supertokens/supertokens-sql-plugin/pull/12