refactor: extract interface for Database Config
supertokens/supertokens-sql-plugin pull request #13
Opened 2022-03-19 23:19 UTC by anugrahsinghal

now each DB config can have a defined set of params it needs to offer
This will be useful for config of multiple DB that
the product needs to support and
different db configs might have different validations in place

2022-03-20 07:19 UTC, rishabhpoddar requested changes

2022-03-20 07:19 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/config/PostgreSQLConfig.java
> +        return "";
This should not be empty.

2022-03-20 07:20 UTC, rishabhpoddar commented
Also please see some of my comments in the other PR. That might affect this one.

2022-03-22 17:20 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/config/PostgreSQLConfig.java
> +        return "";
fix added

2022-03-23 09:47 UTC, rishabhpoddar commented
hey @anugrahsinghal i am closing this PR since this has duplicate code from https://github.com/supertokens/supertokens-sql-plugin/pull/14/files

2022-03-23 09:47 UTC, closed without merging

2022-03-23 09:51 UTC, anugrahsinghal commented
yeah makes sense

did the same changes in the other PR too