(WIP)feat: adds custom naming for hibernate + refactor
supertokens/supertokens-sql-plugin pull request #14
Opened 2022-03-19 23:34 UTC by anugrahsinghal

adds a class to override table names that are mapped to databases
based on config values provided

depends on: #13

2022-03-20 05:51 UTC, rishabhpoddar requested changes

2022-03-20 05:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/config/DatabaseConfig.java
> +public interface DatabaseConfig {
Why do we need this interface? There is always only going to be one config file that is provided by the user, so what advantage does this interface provide?

2022-03-20 05:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/config/PostgreSQLConfig.java
> +    }
We already have a function called `addSchemaAndPrefixToTableName`. So why do we need this?

2022-03-20 05:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/hibernate/HibernateUtils.java
> +    private static SessionFactory newSessionFactory(DatabaseConfig databaseConfig) {
Why not just put this inside `sessionFactory` function above? This function is not being called from many places anyway.

2022-03-20 05:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/hibernate/HibernateUtils.java
> +    private static HikariConfig hikariConfig(DatabaseConfig databaseConfig) {
Since we are refactoring, maybe move this to a different file?

2022-03-20 05:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/hibernate/HibernateUtils.java
> +    public static SessionFactory sessionFactory(DatabaseConfig databaseConfig) {
Rename this to `initSessionFactory`? So that it is clear that this only meant to be called during init and just fetch a session factory that was previously inited.

2022-03-20 05:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/hibernate/HibernateUtils.java
> +    private static final List<Closeable> CLOSEABLES = new ArrayList<>();
The ConnectionPool class is the one that holds a static instance of `sessionFactory`. Therefore, I think that should be the class that also holds this arrayList (or then holds a static instance of `hikariPool` and `sessionFactory` (like it used to).

Furthermore, having some state in a Utils class is weird anyway. So ideally, make the `sessionFactory` take the `DatabaseConfig` and the `DataSource`. The ConnectionPool class forms the datasource first (and stores it in a static var), and passes it to `sessionFactory` which returns the `sessionFactory` (which is also stored in a static var in the ConnectionPool class).

The close function in `ConnectionPool` would then close both of those.

2022-03-20 05:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/config/PostgreSQLConfig.java
> +    }
I see. this is being used in the SupertokensNamingStrategy class. But this should not return an empty string.

2022-03-20 05:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +/*
We can change the name of this file to `CustomNamingStrategy`

2022-03-20 05:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +/*
Also, since you have made a package named Hibernate, should we move the domainobjects package inside this one too?

2022-03-20 05:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +    private String tableName(String name) {
rename function to `legacyTableName`

2022-03-20 05:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +        case "key_value" -> databaseConfig.getKeyValueTable();
Since we have this mapping, does the KeyValueDO.java still have that `@Table(name="...")` annotation in it?

2022-03-20 05:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +        return Identifier.toIdentifier(PREFIX + name.getText());
What about the provided schema? We should just call the `addSchemaAndPrefixToTableName` function from the config here like `return addSchemaAndPrefixToTableName(name.getText());`

2022-03-20 05:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +        case "key_value" -> databaseConfig.getKeyValueTable();
Also, in the KeyValueDO, we have the constraint name that depends on the name of the table as well. How will that be applied dynamically?

2022-03-20 08:40 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +/*
added commit to resolve this

2022-03-20 08:40 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +    private String tableName(String name) {
added commit to resolve this

2022-03-20 08:43 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +        return Identifier.toIdentifier(PREFIX + name.getText());
was not aware of this, copied the code from the old PR, will refactor

2022-03-20 09:46 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +        return Identifier.toIdentifier(PREFIX + name.getText());
hey @rishabhpoddar not sure how this will pan out

the cases in `legacyTableName` call to say `databaseConfig.get*CASE_NAME*Table()` which internally calls `addSchemaAndPrefixToTableName` so calling it explicitly does not make sense

shouldn't the Impl for this look like `return Identifier.toIdentifier(legacyTableName(name.getText()));`

2022-03-20 09:47 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +        return Identifier.toIdentifier(PREFIX + name.getText());
legacyTableName should again be refactored then to `tableNameWithPrefixAndSchema` ?

wdyt ? any suggestions

2022-03-20 10:00 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +        return Identifier.toIdentifier(PREFIX + name.getText());
So the flow is:
- If the `legacyTableName` function returns non-null, we return that name as it is (wrapped with `tableNameWithPrefixAndSchema(..)`. Else
- We call `Identifier.toIdentifier(addSchemaAndPrefixToTableName(name.getText()));`

So this way, we are not doing `addSchemaAndPrefixToTableName` twice. Was this your confusion?

2022-03-20 10:37 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +        return Identifier.toIdentifier(PREFIX + name.getText());
```
func legacyTableName(name) {
   case "kv" : config.getKVName(name);
}

func getKVName(name) {
   return addSchemaAndPrefixToTableName(name);
}
```

the thing to notice here is the function being called in `legacyTableName` already calls `addSchemaAndPrefixToTableName`

so basically `legacyTableName` will return us the name with the `schema` and `prefix` added to it


hence `legacyTableName`is not a legacy table name but _actual fully qualified table name_

2022-03-20 11:24 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/HibernateUtils.java
> +    public static SessionFactory sessionFactory(DatabaseConfig databaseConfig) {
added commit to resolve this

2022-03-20 11:30 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/HibernateUtils.java
> +    private static HikariConfig hikariConfig(DatabaseConfig databaseConfig) {
not sure why this needs to be in a different file?

HikariConfig will only be used with Hibernate, so keeping all config options/functions at the same place is what I am trying to achieve here.

could you elaborate on this

2022-03-20 12:50 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +        return Identifier.toIdentifier(PREFIX + name.getText());
Ah yes. But it only applies to some of the tables and not all. For example, there are passwordless recipe tables (which are newer tables) in which case the `legacyTableName` will return `null`.

For the older tables, `legacyTableName` will not return null, so you don't have to do `addSchemaAndPrefixToTableName` again on them.

If you have a better name rather than `legacyTableName`, please feel free to modify your PR accordingly.

2022-03-21 05:36 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +        return Identifier.toIdentifier(PREFIX + name.getText());
why keep inconsistent behaviors between methods of similar usage?

shouldn't they all behave in a similar way and give the name with all parameters added?

2022-03-21 05:42 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +        case "key_value" -> databaseConfig.getKeyValueTable();
> does the KeyValueDO.java still have that `@Table(name="...")` 

yes, the `name` passed to the function `tableName`  is the value of the `name="..."` from the @Table annotation

2022-03-21 05:47 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +        case "key_value" -> databaseConfig.getKeyValueTable();
> Also, in the KeyValueDO, we have the constraint name that depends on the name of the table as well. How will that be applied dynamically?

have not investigated this

2022-03-21 06:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +        return Identifier.toIdentifier(PREFIX + name.getText());
Ideally, they should. But previously, we didn't have the concept of a prefix. We would allow users to change the table name only by providing the full table name for that table in the config. 

Later on, we got the idea of doing this via a prefix so that each time we add a new table, we don't have to put a config for it. So to maintain backward compatibility, we are doing it this way.

2022-03-21 07:00 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +        case "key_value" -> databaseConfig.getKeyValueTable();
As discussed, we can remove the contraint.

2022-03-21 07:03 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/hibernate/HibernateUtils.java
> +    private static HikariConfig hikariConfig(DatabaseConfig databaseConfig) {
Sure. So we need to close the hikari connection when the close function is called in the connection pool.

This implies that we need to store it as a static variable somewhere. I would like to have all static variables stored in one class (ConnectionPool - as we need to store the sessionFactory static var there anyway).

Therefore, ConnectionPool will first have to create HikariConfig and pass that to HibernateUtils.

Therefore, we should move this to a different class file. Or keep it in ConnectionPool - either is fine.

2022-03-22 17:31 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/HibernateUtils.java
> +    private static SessionFactory newSessionFactory(DatabaseConfig databaseConfig) {
added commit to solve this

2022-03-22 17:45 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/HibernateUtils.java
> +    private static HikariConfig hikariConfig(DatabaseConfig databaseConfig) {
added commit to resolve this

2022-03-22 17:45 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/config/PostgreSQLConfig.java
> +    }
added commit to resolve this

2022-03-22 17:46 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/HibernateUtils.java
> +    private static final List<Closeable> CLOSEABLES = new ArrayList<>();
added commit to resolve this

2022-03-22 17:46 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +/*
not right now

2022-03-22 18:03 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/SupertokensNamingStrategy.java
> +        return Identifier.toIdentifier(PREFIX + name.getText());
added commit to resolve this

2022-03-23 09:58 UTC, rishabhpoddar requested changes

2022-03-23 09:58 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/ConnectionPool.java
> +        final PostgreSQLConfig config = Config.getConfig(start);
```suggestion
        final DatabaseConfig config = Config.getConfig(start);
```

2022-03-23 09:59 UTC, rishabhpoddar commented
Looks good. Just one tiny change.

2022-03-23 10:00 UTC, rishabhpoddar commented
And you will need to run the test action in your repo.

2022-03-23 11:17 UTC, anugrahsinghal commented
ran the tests, all green 💯

2022-03-23 11:58 UTC, rishabhpoddar approved these changes

2022-03-23 12:05 UTC, merged