migrate jwt signing queries
supertokens/supertokens-sql-plugin pull request #37
Opened 2022-07-15 10:49 UTC by anugrahsinghal

2022-07-15 10:52 UTC, anugrahsinghal commented
@rishabhpoddar 

https://github.com/supertokens/supertokens-sql-plugin/pull/37/files#diff-5f72db7c99e6138c265f04d0edf32fd2dde8bc402f7de493e60668e22ddc0666R980-R983


what are your opinions about this ?

2022-07-21 10:29 UTC, rishabhpoddar requested changes

2022-07-21 10:29 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/Start.java
>                  throw new DuplicateKeyIdException();
To discuss this on call

2022-07-21 10:29 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/Start.java
>              // We keep the old exception detection logic to ensure backwards compatibility.
You can remove the old way of doing exception handling

2022-07-21 10:29 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/domainobject/jwtsigning/JWTSigningDO.java
> +    @Column(nullable = false)
Specify length

2022-07-21 10:29 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/domainobject/jwtsigning/JWTSigningDO.java
> +    @Column(columnDefinition = "TEXT")
nullable false

2022-07-21 10:29 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/domainobject/jwtsigning/JWTSigningDO.java
> +
Add comment of raw SQL table schema

2022-07-21 15:07 UTC, rishabhpoddar requested changes

2022-07-21 15:07 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/Start.java
>                  throw new DuplicateKeyIdException();
We can try doing a flush inside `setJWTSigningKeyInfo_Transaction` and that may solve this issue where you don't need to do `if(eTemp instanceof NonUniqueObjectException) {`

2022-07-29 09:04 UTC, anugrahsinghal commented
https://github.com/supertokens/supertokens-sql-plugin/pull/37#discussion_r926789690

For this issue, a `flush` will not be able to help
- The issue originates since we are trying to `save` an entity with `same Id` within the `same` transaction
And since flush does not clear the hibernate cache, this exception is being thrown by hibernate itself

---
Possible Solutions
- Change `ExceptionParsingTest::setJWTSigningKey_TransactionExceptions` to use 2 transactions instead of one to test this scenario, this will make the validation go to the DB 
- Keep this exception handling as-is for now and handle it when we start with designing/improving the exception handling part later on


@rishabhpoddar - WDYT?

2022-07-29 09:11 UTC, rishabhpoddar commented
@anugrahsinghal i think we should keep the test as it is and deal with the exception handling later on.

2022-07-29 09:11 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/Start.java
>                  throw new DuplicateKeyIdException();
https://github.com/supertokens/supertokens-sql-plugin/pull/37#issuecomment-1199052419

2022-07-29 10:24 UTC, rishabhpoddar approved these changes

2022-07-29 10:24 UTC, merged