feat: migrate user metadata queries
supertokens/supertokens-sql-plugin pull request #38
Opened 2022-07-15 17:30 UTC by anugrahsinghal

- [x] create DO for UserMetadata
- [x] migrate queries
- [x] add exception handling for HibernateSpecificException if thrown
- [x] all tests should pass

2022-07-15 17:35 UTC, anugrahsinghal commented
@rishabhpoddar 
https://github.com/supertokens/supertokens-sql-plugin/pull/38/files?diff=split&w=0#diff-981d9fbab5f5567a9f05e4e5e71606df922a6845e30738557c5876a4d7db709aR63-R66

For this query
the last part where `on conflict do set user_metadata=excluded.usermetadata`

will that transform to `entity.setUser_metadata("excluded.usermetadata")` ?

a little confused because `excluded.usermetadata` is not in quotes in the query

2022-07-18 06:41 UTC, anugrahsinghal commented
> will that transform to `entity.setUser_metadata("excluded.usermetadata")` ?
okay found this is a Postgres-specific feature, I will try to find what we can do with it in hibernate.

2022-07-19 15:57 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/UserMetadataQueries.java
> +        return 1;
@rishabhpoddar 

what's your opinion on this?

2022-07-21 09:41 UTC, rishabhpoddar requested changes

2022-07-21 09:41 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/UserMetadataQueries.java
> +        return 1;
Yea. I agree with you that this should not return an `int`. For now though, we can keep it like this. What you did makes sense (feel free to resolve this comment)

2022-07-21 09:41 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/UserMetadataQueries.java
> +        String QUERY = "SELECT entity FROM UserMetadataDO entity WHERE entity.user_id = :user_id";
We should use the session.get function here since it saves the entity in cache, so that when we do session.get in the update function, it doesn't query the db again.

2022-07-21 10:47 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/UserMetadataQueries.java
> +        String QUERY = "SELECT entity FROM UserMetadataDO entity WHERE entity.user_id = :user_id";
okay, will look into this, and make the changes

2022-07-21 12:14 UTC, rishabhpoddar approved these changes

2022-07-21 12:15 UTC, rishabhpoddar commented
This looks good. Will merger after all PR checks have passed

2022-07-21 12:31 UTC, merged