feat: Migrate SessionInfo Queries
supertokens/supertokens-sql-plugin pull request #40
Opened 2022-07-18 09:34 UTC by anugrahsinghal

Migrate SessionInfo Queries to use Hibernate

2022-07-21 08:29 UTC, rishabhpoddar requested changes

2022-07-21 08:29 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/domainobject/session/SessionAccessTokenSigningKeysDO.java
> +
Add a comment with the raw SQL table structure as well.

2022-07-21 08:29 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/domainobject/session/SessionInfoDO.java
> +
Add a comment of the raw SQL table as well.

2022-07-21 08:29 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/domainobject/session/SessionAccessTokenSigningKeysDO.java
> +    private Long created_at_time;
Should we use `long` instead of `Long`? - In other tables, we use `long`

2022-07-21 08:29 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/domainobject/session/SessionInfoDO.java
> +
Same goes for other DOs as well.

2022-07-21 08:29 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/domainobject/session/SessionInfoDO.java
> +    private String session_handle;
We should add a length of 255 to this field.

2022-07-21 09:21 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/domainobject/session/SessionInfoDO.java
> +    private String session_handle;
length is 255 by default for String columns, that's why I have skipped them

2022-07-21 09:31 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/domainobject/session/SessionInfoDO.java
> +    private String session_handle;
I think we should be more explicit. It's always clearer.

2022-07-22 11:04 UTC, rishabhpoddar approved these changes

2022-07-22 11:05 UTC, merged