feat: migrate user roles queries
supertokens/supertokens-sql-plugin pull request #42
Opened 2022-07-20 12:50 UTC by anugrahsinghal

- [x] create domain models
- [x] modify queries
- [x] additional error handling in Start.java
- [x] modify changelog
- [x] all tests should pass
- [x] Entity Null Checks when doing `session.get`
- [x] verify data flow to ensure `session.get` instead of HQL

2022-07-20 14:36 UTC, anugrahsinghal commented
blocked due to issue similar to #36 

failing test [io.supertokens.test.userRoles.UserRolesStorageTest::testAddPermissionToRole_TransactionResponses]

2022-08-02 13:43 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/ConnectionPool.java
> +            } catch (PersistenceException | SQLException | StorageQueryException | StorageTransactionLogicException e) {
`PersistenceException` was added so that issues that occur when doing a commit also get caught

2022-08-02 18:05 UTC, anugrahsinghal commented
so using `session.flush` did solve the issue

> Q. When should we use `session.flush`

My opinion is to not use it everywhere
I think only where we have a custom exception handling logic, where different domain exceptions can be thrown might be a good candidate for doing flushes
That too only in `..._Transaction` methods, as the commit is done later

2022-08-09 06:29 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/hibernate/CustomSessionWrapper.java
>      }
this block should me moved up in this file along with other supported functions. Also can remove the `//`

2022-08-09 06:29 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/ConnectionPool.java
> +            } catch (PersistenceException | SQLException | StorageQueryException | StorageTransactionLogicException e) {
Do we need to do this cause we use flush now whenever needed?

2022-08-09 06:35 UTC, rishabhpoddar requested changes

2022-08-09 06:35 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/UserRolesQueries.java
> +
should we do a flush here as well?

2022-08-09 16:55 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/hibernate/CustomSessionWrapper.java
>      }
done

2022-08-09 16:58 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/UserRolesQueries.java
> +
my thoughts on the usage of flush
https://github.com/supertokens/supertokens-sql-plugin/pull/42#issuecomment-1203053016
---
in line with those

we can, but I do not think we should use flush here

2022-08-09 17:01 UTC, anugrahsinghal commented
> Do we need to do this cause we use flush now whenever needed?
https://github.com/supertokens/supertokens-sql-plugin/pull/42#discussion_r940946503

so um I think we should keep the `PersistenceException` in the catch block 
because it will essentially catch any exception that we might not have handled/faced
but hibernate might convert

it basically works as replacement for `SQLException` here but I don't think we can replace that yet since the interface requires it

2022-08-10 04:48 UTC, rishabhpoddar commented
@anugrahsinghal 

> I think only where we have a custom exception handling logic, where different domain exceptions can be thrown might be a good candidate for doing flushes

What do you mean by "where different domain exceptions can be thrown".

2022-08-10 07:13 UTC, anugrahsinghal commented
domain exceptions as in the `UnknownRoleException` or `DuplicateUserRoleMappingException`
a better word might be custom exceptions I think(but not the generic wrapper like StoragQueryException)

2022-08-10 07:26 UTC, rishabhpoddar commented
Got it. We should modify the contributing to specify this as well. You can make this change in this PR itself.

2022-08-10 07:27 UTC, rishabhpoddar approved these changes

2022-08-10 08:43 UTC, anugrahsinghal commented
have made the changes to the contribution doc too.
take a look and let me know if any ideas for improving the details/language

2022-08-10 09:43 UTC, rishabhpoddar approved these changes

2022-08-10 09:43 UTC, rishabhpoddar commented
Looks good. Thank you

2022-08-10 09:43 UTC, merged