feat: migrate password-less queries
supertokens/supertokens-sql-plugin pull request #43
Opened 2022-07-21 08:04 UTC by anugrahsinghal

2022-07-21 08:17 UTC, anugrahsinghal commented
Issues similar to #36 and 
another issue where
Hibertane is causing a few exceptions
Not-null property references a transient value
need to investigate the fix for this

2022-07-21 15:25 UTC, rishabhpoddar requested changes

2022-07-21 15:25 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +//                session.save(PasswordlessDevicesDO.class, code.deviceIdHash, passwordlessDevicesDO);
Here we should uncomment this, and in `createCode_Transaction`, we should call session.get on Passwordless device, and then save the new code.

We should add a test similar to [this one](https://github.com/supertokens/supertokens-sql-plugin/blob/0.0/src/test/java/io/supertokens/storage/sql/test/HibernateTest.java#L417) where we make sure that when this function is called, there is no select statement that is fired to the db.

2022-07-21 15:25 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
>      }
We do not want to call `createCode_transaction` in here cause that does a session.get. Instead, we can just run a HQL query here

2022-07-22 17:33 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +//                session.save(PasswordlessDevicesDO.class, code.deviceIdHash, passwordlessDevicesDO);
resolving this since we made an explicit call using session.get

2022-07-24 11:04 UTC, rishabhpoddar requested changes

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/Start.java
> +            if (cause.getConstraintName().equalsIgnoreCase("passwordless_users_email_key")) {
The constraint name can change based on the name of the table. So i prefer if we check this constraint failure by first getting the `PSQLException` from it, and then doing:
```java
if (isUniqueConstraintError(((PSQLException) e).getServerErrorMessage(),
                        Config.getConfig(this).getPasswordlessUsersTable(), "email")) {
                    throw new DuplicateEmailException();
                }
```

And then we can remove the `} catch (SQLException e) {` part of this function.

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/Start.java
> +            if (cause.getConstraintName().equalsIgnoreCase("passwordless_users_phone_number_key")) {
The constraint name can change based on the name of the table. So i prefer if we check this constraint failure by first getting the `PSQLException` from it, and then doing:
```java
if (isUniqueConstraintError(((PSQLException) e).getServerErrorMessage(),
                        Config.getConfig(this).getPasswordlessUsersTable(), "phone_number")) {
                    throw new DuplicatePhoneNumberException();
                }
```

And then we can remove the `} catch (SQLException e) {` part of this function.

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/Start.java
> +                throw new DuplicateLinkCodeHashException();
The name of the constraints can change based on the name of the table, so I prefer if we stick to getting the `PSQLException` from the exception and then doing the stuff we do below (in the `} catch (StorageTransactionLogicException e) {` block.

We can then also get rid of `} catch (StorageTransactionLogicException e) {` block.

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/Start.java
> +        } catch (PersistenceException e) {
See other comments in this file.

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/Start.java
> +            ConstraintViolationException cause = (ConstraintViolationException) e.getCause();
See other comments in this file.

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        // @formatter:on
Can we undo the formatting changes here?

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +                + " PRIMARY KEY (device_id_hash));";
Can we undo the formatting changes here?

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
>                  + "(device_id_hash) ON DELETE CASCADE ON UPDATE CASCADE);";
Can we undo the formatting changes here?

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        return query.list().stream().findFirst().map(PasswordlessQueries::entityToPasswordlessDevice).orElse(null);
We should use session.get here since this is happening in a transaction (and there might be other queries that need to also get the device hash), and also cause we are querying based on the primary key.

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        query.executeUpdate();
This is a part of a transaction, so we should do session.get first cause there is already a PasswordlessDevicesDO entity in the session which is not getting updated by this query, so it might cause issues for queries running after this?

So session.get, change the value in memory, and then session.update

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        query.executeUpdate();
Since this is in a transaction, we have to be careful about if there is already an instance of `PasswordlessCodesDO` entity in the session:
- If there is, and we run this delete query, what happens to that instance?
- If there isn't then this is fine.

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
>              return null;
On second thought, instead of throwing a custom formed exception like we are (which is kind of ugly), why not just let session.save throw that exception automatically? I realise that we had said calling session.get explicitly is better, but if we need to throw this kind of manually formed exception, maybe it's not better.

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +                + "= :device_id_hash";
If there is already a `PasswordlessCodesDO` entity in the cache for this session, and we are fetching that again here, what affect will that have on the previously saved item in the cache? Will it be overriden? What if that has some updated value in it (that has not yet been flushed) - will that get lost?

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        query.executeUpdate();
Since this is in a transaction, we have to be careful about if there is already an instance of `PasswordlessCodesDO` entity in the session:
- If there is, and we run this delete query, what happens to that instance?
- If there isn't then this is fine.

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        query.executeUpdate();
Since this is in a transaction, we have to be careful about if there is already an instance of `PasswordlessCodesDO` entity in the session:
- If there is, and we run this delete query, what happens to that instance?
- If there isn't then this is fine.

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +                // we'd only leave devices that will be cleaned up later automatically when they expire.
What do you mean by "even if the user is changed"?

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        String QUERY = "UPDATE PasswordlessUsersDO entity SET entity.email = :email WHERE entity.user_id = :user_id";
If there is already an instance of `PasswordlessUsersDO` in the session, then we should use that instead of running the HQL command? if not, then this is fine.

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +                + ".user_id = :user_id";
If there is already an instance of `PasswordlessUsersDO` in the session, then we should use that instead of running the HQL command? if not, then this is fine.

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +            return query.list().stream().findFirst().map(PasswordlessQueries::entityToPasswordlessDevice).orElse(null);
It doesn't really matter in this case, but since we are querying based on primary key, maybe we should use session.get?

2022-07-24 11:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +            return query.list().stream().findFirst().map(PasswordlessQueries::entityToPasswordlessCode).orElse(null);
Shouldn't matter in this case, but since we are querying based on primary key, we should use session.get?

2022-07-24 12:13 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        return query.list().stream().findFirst().map(PasswordlessQueries::entityToPasswordlessDevice).orElse(null);
is the intent, that the result is cached in L1 cache?
if yes, even using Query syntax the results are cached in L1

2022-07-24 12:17 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
>                  + "(device_id_hash) ON DELETE CASCADE ON UPDATE CASCADE);";
done

2022-07-24 12:17 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +                + " PRIMARY KEY (device_id_hash));";
done

2022-07-24 12:17 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        // @formatter:on
done

2022-07-25 07:32 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
>              return null;
What's also strange is there there is another recipe (userid mapping - it's work in progress), which has a similar case. It needs to insert into a table (C) that has a foreign key constraint on another table (P).

When inserting into (C), we just create a new Entity of type (P) like `new P(..)` and then go about inserting into (C) using `session.save`. If the item in (P) does not exist, hibernate throws a foreign key error (expected). It doesn't do a SELECT query at all in this case. See https://github.com/supertokens/supertokens-sql-plugin/blob/76ea26327d0dde83e6102538a99c9298aa5b5706/src/main/java/io/supertokens/storage/sql/queries/UserIdMappingQueries.java#L58

2022-07-25 07:40 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
>              return null;
I noticed the first param is the PK type not the DO type in `session.save`, why so?

2022-07-25 07:41 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +                + "= :device_id_hash";
making queries using HQL does not bypass Hibernate's L1 cache.

2022-07-25 08:01 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/Start.java
> +            if (cause.getConstraintName().equalsIgnoreCase("passwordless_users_email_key")) {
understand the reasoning for not constraint name changes based on table name.

But I think it would be better to get the **constraint violated name** from the `ConstraintViolationException`(referred as CVE further) itself.

CVE is thrown after the actual server exception is translated by the hibernate library
and keeping the extension view in place that we need to make this module work for multiple DB's going forward, I think using CVE would be a better choice


A point of concern can be what are the details that hibernate checks, the details and the Impl can be found here
`org.hibernate.exception.internal.SQLStateConversionDelegate`
From What I could gather, it compares SQLCodes for the DB and the messages too
see the extensions for different `org.hibernate.dialect.Dialect`, they have a `getViolatedConstraintNameExtracter()` which helps with that.

2022-07-25 08:03 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/Start.java
> +            if (cause.getConstraintName().equalsIgnoreCase("passwordless_users_email_key")) {
we can create another function and compare just the violated constraint name 
something like
```
if(isUniqueConstraintError(e.getConstraintName(),Config.getConfig(this).getPasswordlessUsersTable(), "email")) {
                    throw new DuplicateEmailException();
                }
                ```

2022-07-25 08:09 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/Start.java
> +            if (cause.getConstraintName().equalsIgnoreCase("passwordless_users_email_key")) {
As for `SQLException` yes that makes sense too.

I think it cannot be eliminated fully right now because the `WithSession` interface throws `SQLE` in its definition.

Thus I think it would be better covered in a follow-up PR to clean up the SQLException altogether and migrate to `PersistenceException` _probably_.

WDYT ?

2022-07-25 08:10 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/Start.java
> +            if (cause.getConstraintName().equalsIgnoreCase("passwordless_users_phone_number_key")) {
See other comments in this file.

2022-07-25 08:11 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/Start.java
> +                throw new DuplicateLinkCodeHashException();
See other comments in this file.
like `SQLExeception`
`StorageTransactionLogicException` is in the contract of `WithSessionForComplexTransaction` which cannot be eliminated fully without refactoring the interface itself

2022-07-25 08:11 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/Start.java
> +        } catch (PersistenceException e) {
See other comments in this file.

2022-07-25 08:12 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/Start.java
> +            ConstraintViolationException cause = (ConstraintViolationException) e.getCause();
See other comments in this file.

2022-07-25 08:19 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
>              return null;
for the manually formed exception.
There is another way to make `session.save` act as it should

`session.getReference()` which does not return a null, but internally handles that the entity is not found and throws the exception itself for the `ConstrainViolation`

we do not have it implemented in our wrapper, but I tested it out by doing 
`sessionWrapper.getSessionImpl().getReference(...)`

but then we'll have to add Impl for the `getRefernce` and functionality to support the `NullCache` too

WDYT ?

2022-07-25 08:35 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +                // we'd only leave devices that will be cleaned up later automatically when they expire.
This comment was copied over from inmemoryDB/PasswordlessQueries.java

now as to why the impl was a little changed.

earlier the code was doing
```java
String QUERY = "DELETE FROM " + Config.getConfig(start).getPasswordlessUsersTable()
            + " WHERE user_id = ? RETURNING user_id, email, phone_number, time_joined";
    
    user = execute(sqlCon, QUERY, pst -> pst.setString(1, userId), result -> {
        if (result.next()) {
            return UserInfoRowMapper.getInstance().mapOrThrow(result);
        }
        return null;
    });
```

---

the below impl is changed by adding `UserInfo user = getUserById(start, userId);`
because earlier we had a `RETURNING` syntax by postgres, not supported by hibernate.

we need that data to do the further operation based on user email and phoneNumber

2022-07-25 10:55 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
>              return null;
the DO and PK thing don't really matter right ?
I see they are only used for the custom cache.

2022-07-25 10:55 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
>              return null;
but I am still really curious as to why it is done like that

the ideal form of the method should be 
`public <T> Serializable save(Class<T> theClass, Serializable id, T object)`
but it instead is
`public <T> Serializable save(Class<T> theClass, Serializable id, Object object)`

why the `Object` type ? and not `T`

2022-07-25 10:55 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
>              return null;
I think this might be bcoz the PK in UserId is a `composite PK (more than 1 field)` and that is considered as a new `PK` altogether which the DB validates
(thinking out loud, not sure)

2022-07-25 10:55 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
>              return null;
it works if you do change the entities like so
```
public class PCDO_PK implements Serializable {

	@Column(length = 44)
	private String code_id;

	@Getter(AccessLevel.PRIVATE)
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id_hash", referencedColumnName = "device_id_hash", nullable = false, unique = true)
	@OnDelete(action = OnDeleteAction.CASCADE)
	private PasswordlessDevicesDO passwordlessDevice;
	
	// other stuff omitted
}
	
public class PasswordlessDevicesDO extends PrimaryKeyFetchable {

    @EmbeddedId
    private PDDO_PK pk;
    
    // other stuff omitted
}
```

2022-07-25 10:55 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
>              return null;
so did some investigation.
The entity constraint for above style(i.e. composite) is not validated by hibernate, but when DB query is fired i.e. the FKey constraint error comes from DB and not Hibernate.
error will throw when we do `session.commit()`

---

but when we do the current impl for Passwordless, the FKey error comes from hibernate as it is not able to find the FKey association in the PersistenceContext.

error will throw when we do `session.save()`

`UnresolvedEntityInsertActions::checkNoUnresolvedActionsAfterOperation` -> `NonNullableTransientDependencies` is where the check happens

2022-07-25 11:21 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/Start.java
> +            if (cause.getConstraintName().equalsIgnoreCase("passwordless_users_email_key")) {
I think we should stick with not using `ConstraintViolationException` right now and follow the same error handling logic as we had. 

Once all the queries are migrated, we can work on error handling as an entirely different set of PRs, and then we can switch over to using `ConstraintViolationException` (which I would very much like to do). 

But keeping these PRs scoped, we should follow the same error handling logic as before.

2022-07-25 11:23 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/Start.java
> +            if (cause.getConstraintName().equalsIgnoreCase("passwordless_users_phone_number_key")) {
See my other comment.

2022-07-25 11:23 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/Start.java
> +                throw new DuplicateLinkCodeHashException();
See my other comment.

2022-07-25 11:23 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/Start.java
> +        } catch (PersistenceException e) {
See my other comment. (haha.. this is just funny)

2022-07-25 11:23 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/Start.java
> +            ConstraintViolationException cause = (ConstraintViolationException) e.getCause();
See my other comment. (haha.. this is just funny)

2022-07-25 11:25 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        return query.list().stream().findFirst().map(PasswordlessQueries::entityToPasswordlessDevice).orElse(null);
Yes, but using query cache does not cache it if the result from this is null (since we have made our own null cache)

2022-07-25 11:49 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
>              return null;
> I noticed the first param is the PK type not the DO type in session.save, why so?

This was a mistake. Thanks for pointing this out.

> the DO and PK thing don't really matter right ? I see they are only used for the custom cache.

Yes, you are right. It doesn't really matter 

> why the Object type ? and not T

Makes sense. 

> why the Object type ? and not T

Good idea. We will make this change now.

> but then we'll have to add Impl for the getRefernce and functionality to support the NullCache too

Uhmm. I prefer not using getReference since it's very hard to communicate when to use it and when not.

> The entity constraint for above style(i.e. composite) is not validated by hibernate, but when DB query is fired i.e. the FKey constraint error comes from DB and not Hibernate.

Is there a way to tell hibernate not to validate the foreign key stuff even if it NOT a composite type? 

----------
All things considered, if we have to stick to the current method, we can throw something like:
```
throw new PersistenceException(new ForeignKeyConstraintNotMetException());
```

where `ForeignKeyConstraintNotMetException` is a new error type we have defined. And then in Start.java, we can unwrap `PersistenceException` and check for this specific exception type.

On the other hand, we can keep the code the way it is now, and then figure this stuff out later when we do error handling after all query migrations are done (in this case, we should create an issue about this specific problem in this repo highlighting that this type of manual error creation should not be done)

I leave it up to you :)

2022-07-25 16:32 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/Start.java
> +            if (cause.getConstraintName().equalsIgnoreCase("passwordless_users_email_key")) {
okay yes makes sense, those can focus exclusively on Exception Handling

2022-07-25 16:33 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/Start.java
> +        } catch (PersistenceException e) {
🤣

2022-07-25 16:40 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        return query.list().stream().findFirst().map(PasswordlessQueries::entityToPasswordlessDevice).orElse(null);
done

2022-07-25 16:42 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        query.executeUpdate();
done

2022-07-25 16:49 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        query.executeUpdate();
`PasswordlessDevicesDO` was already in the transaction.
Have used `session.get`

done.

2022-07-25 17:05 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        query.executeUpdate();
Instance is there in transaction, but I don't think we'll need to explicitly take care of it(Hibernate will), the usecase will not qualify for `Null Cache`.

In usecase `Passwordless::removeCode` 
the operation `getCodesOfDevice_Transaction` gets the entities(by HQL) but not by PKey(thus does not qualify for null cache).
the later it calls `deleteCode_Transaction` that is this function, also using HQL.
so Hibernate will take care of syncing data.

2022-07-25 17:07 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        query.executeUpdate();
we could do a `session.get` and then delete, but mostly should not matter.

WDYT ?

2022-07-25 17:14 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        String QUERY = "UPDATE PasswordlessUsersDO entity SET entity.email = :email WHERE entity.user_id = :user_id";
1. `updateUserEmail_Transaction` and `updateUserPhoneNumber_Transaction` are done in same transaction.
2. But those results are not used anywhere else

first `updateUserEmail_Transaction` 
and then `updateUserPhoneNumber_Transaction` is called

If we do a `session.get` then will 
Q1. it would be in `updateUserEmail_Transaction` right?
Q2. do we need to do a PessimisticWrite Lock too in the same function?

OR 

since entity is not really fetched in the transaction in the old Impl we can leave this be ?

2022-07-25 17:26 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +                + ".user_id = :user_id";
https://github.com/supertokens/supertokens-sql-plugin/pull/43/files?diff=split&w=1#r929118423

2022-07-25 17:27 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +            return query.list().stream().findFirst().map(PasswordlessQueries::entityToPasswordlessDevice).orElse(null);
done

2022-07-25 17:28 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +            return query.list().stream().findFirst().map(PasswordlessQueries::entityToPasswordlessCode).orElse(null);
done

2022-07-25 17:48 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/Start.java
> +            if (cause.getConstraintName().equalsIgnoreCase("passwordless_users_email_key")) {
done

2022-07-25 17:48 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/Start.java
> +            if (cause.getConstraintName().equalsIgnoreCase("passwordless_users_phone_number_key")) {
done

2022-07-25 17:48 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/Start.java
> +                throw new DuplicateLinkCodeHashException();
done

2022-07-25 17:48 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/Start.java
> +        } catch (PersistenceException e) {
done

2022-07-25 17:48 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/Start.java
> +            ConstraintViolationException cause = (ConstraintViolationException) e.getCause();
done

2022-07-25 17:54 UTC, anugrahsinghal commented
@rishabhpoddar 

since the new exception handling can be useful later, I have just commented them out instead of deleting them.
LMK if you want me to delete those.

2022-07-25 18:18 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
>              return null;
in which module will `new ForeignKeyConstraintNotMetException()` go ?

`sql-plugin` or `plugin-interface` ?

throwing the custom exception seems like a wiser choice, since for this module we are anyway reverting to PSQL exception, and creating that level of nesting will just make this unpleasant.
---

another way could be direct `throw FKeyEx...()` that way we will be having a catch block in the handler code, and not have to do branches for type of unwrapped exception when handling the actual use-case data.

2022-07-26 05:46 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        final PasswordlessDevicesDO passwordlessDevicesDO = session.get(PasswordlessDevicesDO.class, deviceIdHash);
Need to check for if this is null or not - if it is null, do nothing

2022-07-26 05:46 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +            final PasswordlessCodesDO passwordlessCodesDO = session.get(PasswordlessCodesDO.class, codeId);
need to check if this is null or not

2022-07-26 05:46 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        final PasswordlessDevicesDO passwordlessDevicesDO = session.get(PasswordlessDevicesDO.class, deviceIdHash,
need to check if this is null or not

2022-07-26 05:46 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        final PasswordlessDevicesDO passwordlessDevicesDO = session.get(PasswordlessDevicesDO.class, deviceIdHash);
need to check if this is null or not

2022-07-26 05:46 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        session.save(PasswordlessCodesDO.class, code.id, toInsert);
Consider removing this function and moving its logic inside the transaction of createDeviceWithCode function.

2022-07-26 05:46 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +            final PasswordlessDevicesDO passwordlessDevicesDO = session.get(PasswordlessDevicesDO.class, deviceIdHash);
need to check for null

2022-07-26 05:46 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
>              return null;
> module sql-plugin will contain the new ForeignKeyConstraintNotMetException() right ?

Yes correct. This exception is only meant to communicate what happened inside a transaction to the Start.java class - so that it can throw the correct type of exception.

> another way could be direct throw FKeyEx...() that way we will be having a catch block in the handler code, and not have to do branches for type of unwrapped exception when handling the actual use-case data.

But then you would have to change the func signature of `ConnectionPool.withSession` function - which we can do later (during the error handling PRs, but not now). We can also make `FKeyEx` a runtime exception, but I prefer not doing that cause runtime exceptions usually should yield a 500 error to the client and not be propagate "expected" errors.

2022-07-26 05:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        query.executeUpdate();
Sounds good. We can keep it this way

2022-07-26 05:49 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        String QUERY = "UPDATE PasswordlessUsersDO entity SET entity.email = :email WHERE entity.user_id = :user_id";
We can keep it the way it is.

2022-07-26 05:53 UTC, rishabhpoddar commented
@anugrahsinghal i have also updated the base branch with a few of the recommendations from your comments (Using `T` instead of `Object` in the `session.save` function..) So please merge that into this branch.

2022-07-26 07:01 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        final PasswordlessDevicesDO passwordlessDevicesDO = session.get(PasswordlessDevicesDO.class, deviceIdHash);
done

2022-07-26 07:01 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +            final PasswordlessCodesDO passwordlessCodesDO = session.get(PasswordlessCodesDO.class, codeId);
done

2022-07-26 07:02 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        final PasswordlessDevicesDO passwordlessDevicesDO = session.get(PasswordlessDevicesDO.class, deviceIdHash,
done

2022-07-26 07:03 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        final PasswordlessDevicesDO passwordlessDevicesDO = session.get(PasswordlessDevicesDO.class, deviceIdHash);
done

2022-07-26 07:04 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        session.save(PasswordlessCodesDO.class, code.id, toInsert);
done

2022-07-26 07:04 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +            final PasswordlessDevicesDO passwordlessDevicesDO = session.get(PasswordlessDevicesDO.class, deviceIdHash);
done

2022-07-26 07:19 UTC, anugrahsinghal commented
> @anugrahsinghal i have also updated the base branch with a few of the recommendations from your comments (Using `T` instead of `Object` in the `session.save` function..) So please merge that into this branch.

will do a rebase on 0.0 once all changes are finalized for the PR

2022-07-30 10:42 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
>              return null;
done

2022-07-30 10:56 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        query.executeUpdate();
#todo

2022-08-01 09:42 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/queries/PasswordlessQueries.java
> +        query.executeUpdate();
done.

2022-08-02 05:52 UTC, rishabhpoddar requested changes

2022-08-02 05:52 UTC, rishabhpoddar commented on src/main/java/io/supertokens/storage/sql/domainobject/passwordless/PasswordlessCodesDO.java
> +        }
Should we do this trimming for all the string fields in all the DOs and PKs? And maybe remove the automatic `@Getter`?

2022-08-02 10:04 UTC, rishabhpoddar approved these changes

2022-08-02 10:18 UTC, anugrahsinghal commented on src/main/java/io/supertokens/storage/sql/domainobject/passwordless/PasswordlessCodesDO.java
> +        }
done, we do not need this now.
opened #47 to find the details

2022-08-02 10:45 UTC, merged